version: '3'
services:
    web:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./web/cert.pem:/cert.pem:ro
            - ./web/key.pem:/key.pem:ro
            - ./web/certbot_challenge:/var/certbot_challenge:ro
            - ./web/www:/var/www:ro
        links:
            - app_nodejs:app_nodejs
            - app_flask:app_flask
    db:
        image: mysql
        volumes:
            - ./db/contents:/var/lib/mysql
            - ./db/backups:/backups
            - ./db/entrypoint:/docker-entrypoint-initdb.d:ro
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file:
            - ./env
    queue:
        image: redis
    app_nodejs:
        build: ./app_nodejs
        links:
            - db:db
            - queue:queue
        volumes:
            - ./app_nodejs/src:/src
        env_file:
            - ./env
    app_flask:
        build: ./app_flask
        command: python ./wsgi.py
        links:
            - db:db
            - queue:queue
        volumes:
            - ./app_flask/src:/src
        env_file:
            - ./env
    worker:
        build: ./worker
        links:
            - queue:queue
        env_file:
            - ./env
        volumes:
            - ./worker/src:/src
